name: Manual Test Workflow

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select the test type'
        required: true
        default: 'all'
        options:
          - all
          - login

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install selenium

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.test_type }}" = "all" ]; then
            pytest
          else
            pytest -k "${{ github.event.inputs.test_type }}"
          fi
